### ISSUE TITLE
Need popup on JSON entry screen to describe the resource and its contents

### ISSUE THREAD

**Issue by hsolbrig** [ebmonfhir/fhir#2]
Hovertext is needed in the JSON creation screen to get a better idea what goes in

**Comment by Khalid-Shahin** [comment]
I'll try to add this feature and make a couple other changes to the JSON Tree Writer this weekend.

When we get to the stage where we create more specialized forms that aren't One-to-One from the data entry fields to the JSON, it'll be more intuitive for the user.

**Comment by Khalid-Shahin** [comment]
I added a hover feature where the Evidence JSON also contains an additional field for each field that would contain the hover text. The hover field would be at the same hierarchy as the corresponding field and it would have the field name + "---HoVeR" at the end. For example:
  "resourceType": "Evidence",
  "resourceType---HoVeR": "this is the hover text for Resource Type",

We just need to fill in the descriptions for all the fields: https://github.com/Khalid-Shahin/JSON-Tree-Writer/blob/master/blank%20Evidence%20template%20with%20blank%20hover%20text.json

Once we fill it out this JSON can be loaded into my JSON Tree Writer (using either the JSON panel and/or we can hard code the JSON into here): https://khalid-shahin.github.io/JSON-Tree-Writer/JSON_Tree_Writer-EBMonFHIR-Evidence-with-Hover-Text.html

**Comment by Khalid-Shahin** [comment]
There’s hover text fields for these two pages:

https://khalid-shahin.github.io/JSON-Tree-Writer/JSON_Tree_Writer-EBMonFHIR-Evidence.html

https://khalid-shahin.github.io/JSON-Tree-Writer/JSON_Tree_Writer-EBMonFHIR-Evidence_Artur's_Example.html

We can also later add hover text fields for the EvidenceVariable resource.

**Comment by Khalid-Shahin** [comment]
Updated it for the Statistic resource. Most of the fields in the JSON Tree Writer have hover text now.

https://khalid-shahin.github.io/JSON-Tree-Writer/JSON_Tree_Writer-EBMonFHIR-Statistic-Resource.html
https://khalid-shahin.github.io/JSON-Tree-Writer/JSON_Tree_Writer-EBMonFHIR-Statistic_Artur%27s_Example_01_Comparative.html

And the other Statistic examples as well.
