### ISSUE TITLE
Precision estimate level

### ISSUE THREAD

**Issue by hsolbrig** [ebmonfhir/fhir#4]
Should `statistic.from` and `statistic.to` be children of `precisionEstimate.level`?

**Comment by Khalid-Shahin** [comment]
Nope, level needs to be a decimal as well . For example 95% CI 0.54 to 10.5 would be coded as.
"precisionEstimate": {
   "type": "CI CodeableConcept",
   "level": 0.95,
   "to": 0.54,
   "from": 10.5
}

We're using 0.95 to describe 95% CI.
